[general]
port = 5801
bind = [
    "::",
    "192.168.40.100"
]
log_level = "DEBUG"

[zeroconf]
name = "_iodongle"

[services.keyboard]
device = "/dev/hidg0"

[services.pointer]
device = "/dev/hidg1"

[services.video]
server = '192.168.40.1:8554'
device = "/dev/video0"
stderr = '/var/log/nug-dongle/video.stderr.log'
stdout = '/var/log/nug-dongle/video.stdout.log'

#[syslog]
#ip = "127.0.0.1"
#port = 1514
